export const SALE_DATA = [
  { day: 'Monday', sales: 18 },
  { day: 'Tuesday', sales: 12 },
  { day: 'Wednesday', sales: 6 },
  { day: 'Thursday', sales: 9 },
  { day: 'Friday', sales: 12 },
  { day: 'Saturday', sales: 3 },
  { day: 'Sunday is not funday not a funday', sales: 9 },

  { day: 'Monday 1', sales: 18 },
  { day: 'Tuesday 1', sales: 12 },
  { day: 'Wednesday 1', sales: 6 },
  { day: 'Thursday 1', sales: 9 },
  { day: 'Friday 1', sales: 12 },
  { day: 'Saturday 1', sales: 3 },
  { day: 'Sunday 1 is not funday not a funday', sales: 9 },

  { day: 'Monday 2', sales: 18 },
  { day: 'Tuesday 2', sales: 12 },
  { day: 'Wednesday 2', sales: 6 },
  { day: 'Thursday 2', sales: 9 },
  { day: 'Friday 2', sales: 12 },
  { day: 'Saturday 2', sales: 3 },
  { day: 'Sunday 2 is not funday not a funday', sales: 9 },

  { day: 'Monday 3', sales: 18 },
  { day: 'Tuesday 3', sales: 12 },
  { day: 'Wednesday 3', sales: 6 },
  { day: 'Thursday 3', sales: 9 },
  { day: 'Friday 3', sales: 12 },
  { day: 'Saturday 3', sales: 3 },
  { day: 'Sunday 3 is not funday not a funday', sales: 9 },

  { day: 'Monday 4', sales: 18 },
  { day: 'Tuesday 4', sales: 12 },
  { day: 'Wednesday 4', sales: 6 },
  { day: 'Thursday 4', sales: 9 },
  { day: 'Friday 4', sales: 12 },
  { day: 'Saturday 4', sales: 3 },
  { day: 'Sunday 4 is not funday not a funday', sales: 9 },

  { day: 'Monday 5', sales: 18 },
  { day: 'Tuesday 5', sales: 12 },
  { day: 'Wednesday 5', sales: 6 },
  { day: 'Thursday 5', sales: 9 },
  { day: 'Friday 5', sales: 12 },
  { day: 'Saturday 5', sales: 3 },
  { day: 'Sunday 5 is not funday not a funday', sales: 9 },

  { day: 'Monday 6', sales: 18 },
  { day: 'Tuesday 6', sales: 12 },
  { day: 'Wednesday 6', sales: 6 },
  { day: 'Thursday 6', sales: 9 },
  { day: 'Friday 6', sales: 12 },
  { day: 'Saturday 6', sales: 3 },
  { day: 'Sunday 6 is not funday not a funday', sales: 9 },

  { day: 'Monday 7', sales: 18 },
  { day: 'Tuesday 7', sales: 12 },
  { day: 'Wednesday 7', sales: 6 },
  { day: 'Thursday 7', sales: 9 },
  { day: 'Friday 7', sales: 12 },
  { day: 'Saturday 7', sales: 3 },
  { day: 'Sunday 7', sales: 9 },

  { day: 'Monday 8', sales: 18 },
  { day: 'Tuesday 8', sales: 12 },
  { day: 'Wednesday 8', sales: 6 },
  { day: 'Thursday 8', sales: 9 },
  { day: 'Friday 8', sales: 12 },
  { day: 'Saturday 8', sales: 3 },
  { day: 'Sunday 8 is not funday not a funday', sales: 9 },

  { day: 'Monday 9', sales: 18 },
  { day: 'Tuesday 9', sales: 12 },
  { day: 'Wednesday 9', sales: 6 },
  { day: 'Thursday 9', sales: 9 },
  { day: 'Friday 9', sales: 12 },
  { day: 'Saturday 9', sales: 3 },
  { day: 'Sunday 9', sales: 9 },
];
