export const RAW_BAR_DATA = [
  { color: 'Red 1', votes: 12 },
  { color: 'Blue 2', votes: 19 },
  { color: 'Yellow 3', votes: 3 },
  { color: 'Green 4', votes: 5 },
  { color: 'Purple 5', votes: 2 },
  // { color: 'Orange 6', votes: 3 },
  // { color: 'Pink 7', votes: 8 },
  // { color: 'Teal 8', votes: 14 },
  // { color: 'Cyan 9', votes: 9 },
  // { color: 'Brown 10', votes: 11 },
  // { color: 'Red 11', votes: 15 },
  // { color: 'Blue 12 Blue 12 Blue 12', votes: 7 },
  // { color: 'Yellow 13', votes: 18 },
  // { color: 'Green 14', votes: 6 },
  // { color: 'Purple 15', votes: 10 },
  // { color: 'Orange 16', votes: 4 },
  // { color: 'Pink 17', votes: 9 },
  // { color: 'Teal 18', votes: 16 },
  // { color: 'Cyan 19', votes: 5 },
  // { color: 'Brown 20', votes: 12 },
  // { color: 'Red 21', votes: 8 },
  // { color: 'Blue 22', votes: 17 },
  // { color: 'Yellow 23 Yellow 23 Yellow 23 Yellow 23 Yellow 23', votes: 6 },
  // { color: 'Green 24', votes: 13 },
  // { color: 'Purple 25', votes: 2 },
  // { color: 'Orange 26', votes: 11 },
  // { color: 'Pink 27', votes: 7 },
  // { color: 'Teal 28', votes: 10 },
  // { color: 'Cyan 29', votes: 9 },
  // { color: 'Brown 30', votes: 5 },
  // { color: 'Red 31', votes: 14 },
  // { color: 'Blue 32', votes: 12 },
  // { color: 'Yellow 33', votes: 3 },
  // { color: 'Green 34', votes: 19 },
  // { color: 'Purple 35', votes: 8 },
  // { color: 'Orange 36', votes: 15 },
  // { color: 'Pink 37', votes: 6 },
  // { color: 'Teal 38', votes: 9 },
  // { color: 'Cyan 39', votes: 4 },
  // { color: 'Brown 40', votes: 10 },
  // { color: 'Red 41', votes: 7 },
  // { color: 'Blue 42', votes: 18 },
  // { color: 'Yellow 43', votes: 13 },
  // { color: 'Green 44', votes: 11 },
  // { color: 'Purple 45', votes: 6 },
  // { color: 'Orange 46', votes: 14 },
  // { color: 'Pink 47', votes: 9 },
  // { color: 'Teal 48', votes: 16 },
  // { color: 'Cyan 49', votes: 5 },
  // { color: 'Brown 50', votes: 12 },
  // { color: 'Red 51', votes: 8 },
  // { color: 'Blue 52', votes: 17 },
  // { color: 'Yellow 53', votes: 6 },
  // { color: 'Green 54', votes: 13 },
  // { color: 'Purple 55', votes: 2 },
  // { color: 'Orange 56', votes: 11 },
  // { color: 'Pink 57', votes: 7 },
  // { color: 'Teal 58', votes: 10 },
  // { color: 'Cyan 59', votes: 9 },
  // { color: 'Brown 60', votes: 5 },
  // { color: 'Red 61', votes: 14 },
  // { color: 'Blue 62', votes: 12 },
  // { color: 'Yellow 63', votes: 3 },
  // { color: 'Green 64', votes: 19 },
  // { color: 'Purple 65', votes: 8 },
  // { color: 'Orange 66', votes: 15 },
  // { color: 'Pink 67', votes: 6 },
  // { color: 'Teal 68', votes: 9 },
  // { color: 'Cyan 69', votes: 4 },
  // { color: 'Brown 70', votes: 10 },
  // { color: 'Red 71', votes: 7 },
  // { color: 'Blue 72', votes: 18 },
  // { color: 'Yellow 73', votes: 13 },
  // { color: 'Green 74', votes: 11 },
  // { color: 'Purple 75', votes: 6 },
];
